<?php declare(strict_types=1);

namespace Jh\ImageAdapter\Image;

use Magento\Framework\Image\Factory as OriginalFactory;

/**
 * Extended to try creating the image with the mock handler if it fails the first time.
 *
 * @author Max Bucknell <max@wearejh.com>
 */
class Factory extends OriginalFactory
{
    public function create($fileName = null, $adapterName = null)
    {
        try {
            return parent::create($fileName, $adapterName); // TODO: Change the autogenerated stub
        } catch (\Exception $e) {
            return parent::create($fileName, 'mock');
        }
    }
}
